version: "3"
services:
  runners-app:
    build: .
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=runners_db'
      - 'POSTGRES_PASSWORD=postgres'
    depends_on:
      db:
        condition: service_started
    restart: on-failure
    ports:
      - '8080:8080'
      - '9000:9000'

  db:
    image: 'postgres:15-alpine'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=runners_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate:v4.15.2
    volumes:
      - ./db/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:postgres@db:5432/runners_db?sslmode=disable",
      ]
    command: ["up"]
    depends_on:
      db:
        condition: service_started
    restart: on-failure